# Generated by Django 3.2.5 on 2021-10-19 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectapp',
            name='description',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
